name: Publish FastMCP AI Agent Bridges to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
      
      - name: "Install"
        run: uv sync --locked --group dev

      - name: "Build"
        run: uv build

      - name: "Publish to PyPi"
        run: uv publish -v dist/*

  publish_sub_packages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        package:
          - fastmcp-ai-agent-bridge-pydantic-ai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
      
      - name: "Install ${matrix.package}"
        run: uv sync --locked --group dev
        working-directory: ${{ matrix.package }}

      # - name: "Test ${matrix.package}"
      #   run: uv run pytest tests
      #   working-directory: ${{ matrix.package }}
      #   env:
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: "Build ${matrix.package}"
        working-directory: ${{ matrix.package }}
        run: uv build

      - name: "Publish to PyPi ${matrix.package}"
        run: uv publish -v dist/*